pipeline { 
  agent {
    label 'agent1'
  }

  stages {
    stage('Build') {
      steps {
        sh('''
          python ./prob3/ci/scripts/cksum.py > checksums.json
          cat checksums.json
         ''')
      }
    }
  }
}
