pipeline { 
  agent {
    label 'agent1'
  }

  stages {
    stage('Build') {
      steps {
        sh('''
          python ./prob3/ci/scripts/cksum.py > checksums.json
          cat checksums.json
         ''')
      }
    }

    stage('Commit') {
      environment { 
        BRANCH = "master"
      }
      steps {
        sh('''
          git checkout -B $BRANCH
          git config user.name 'jenkins-ci'
          git config user.email 'jenkins-ci-user@users.noreply.example.com'
          git add . && git commit -am "[JENKINS_CI] add/update repo md4 checksum file"
        ''')
      }
    }

    stage('Push') {
      environment {
        BRANCH = "master"
      }

      steps {
        withCredentials([usernamePassword(credentialsId: 'effective-robot',
        usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
          sh('''
            echo "username=$GIT_USERNAME  password=$GIT_PASSWORD"
            git config --local credential.helper "!f() { echo username=\\$GIT_USERNAME; echo password=\\$GIT_PASSWORD; }; f"
            git config --local --list
            git push origin HEAD:$BRANCH
          ''')
        }
      }
    }
  }
}
